# --- !Ups

create table "exchange_result" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "currency_to" varchar not null,
  "currency_from" varchar not null,
  "amount" DOUBLE ,
  "rate" DOUBLE ,
  "created_date" timestamp
);

# --- !Downs
drop table "exchange_result" if exists;
